name: "AccuKnox Secret Scan"
description: "Run AccuKnox Secret Security scan on a repository"

branding: 
  icon: "shield" 
  color: "purple"

inputs:
  accuknox_token:
    description: "CSPM token"
    required: true
  accuknox_endpoint:
    description: "CSPM Console endpoint URL"
    required: true
  accuknox_label:
    description: "Label for scan results in AccuKnox Console"
    required: true
  results:
    description: "Which result types to include: verified, unknown, unverified, filtered_unverified"
    required: false
    default: ""
  branch:
    description: "Git branch to scan. Use 'all-branches' to scan all branches"
    required: false
    default: ""
  exclude_paths:
    description: "Comma-separated list of paths to exclude from scanning"
    required: false
    default: ""
  additional_arguments:
    description: "Extra arguments to pass to the secret scanning tool"
    required: false
    default: ""
  soft_fail:
    description: "Do not return an error code if there are failed checks"
    required: false
    default: false
  base_command:
    description: "Override the base command used to run the scan (optional)"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Run AccuKnox Secret Scan
      shell: bash
      env:
        ACCUKNOX_TOKEN: ${{ inputs.accuknox_token }}
        ACCUKNOX_LABEL: ${{ inputs.accuknox_label }}
        ACCUKNOX_ENDPOINT: ${{ inputs.accuknox_endpoint }}
        RESULTS: ${{ inputs.results }}
        BRANCH: ${{ inputs.branch }}
        EXCLUDE_PATHS: ${{ inputs.exclude_paths }}
        ADDITIONAL_ARGUMENTS: ${{ inputs.additional_arguments }}
        SOFT_FAIL: ${{ inputs.soft_fail }}
        BASE_COMMAND: ${{ inputs.base_command }}
      run: |
        set -e

        if [ -z "$ACCUKNOX_TOKEN" ] || [ -z "$ACCUKNOX_LABEL" ] || [ -z "$ACCUKNOX_ENDPOINT" ]; then
          echo "ERROR: token, label, and endpoint must be provided!"
          exit 1
        fi

        echo "Downloading AccuKnox ASPM Scanner..."
        curl -L https://github.com/accuknox/aspm-scanner-cli/releases/download/v0.13.4/accuknox-aspm-scanner -o accuknox-aspm-scanner
        chmod +x accuknox-aspm-scanner

        # Soft fail argument
        SOFT_FAIL="${SOFT_FAIL//[$'\t\r\n ']}"
        SOFT_FAIL_ARG=""
        if [ "$SOFT_FAIL" = "true" ]; then
          SOFT_FAIL_ARG="--softfail"
        fi

        # Build base command
        BASE_CMD="git file://."
        if [ -n "$BASE_COMMAND" ]; then
          BASE_CMD="$BASE_COMMAND"
        fi

        # Add optional CLI arguments
        ARGS=""
        [ -n "$RESULTS" ] && ARGS="$ARGS --results $RESULTS"
        [ -n "$BRANCH" ] && ARGS="$ARGS --branch $BRANCH"
        [ -n "$EXCLUDE_PATHS" ] && ARGS="$ARGS --exclude-paths $EXCLUDE_PATHS"
        [ -n "$ADDITIONAL_ARGUMENTS" ] && ARGS="$ARGS $ADDITIONAL_ARGUMENTS"

        echo "Running AccuKnox secret scan..."
        echo "./accuknox-aspm-scanner scan $SOFT_FAIL_ARG secret --command \"$BASE_CMD $ARGS\" --container-mode"
        ./accuknox-aspm-scanner scan $SOFT_FAIL_ARG secret --command "$BASE_CMD $ARGS" --container-mode
      
